version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                docker info
                if [[ -e ~/docker/image.tar ]]; then docker load --input ~/docker/image.tar; fi
                docker build --rm=false -t jonathanschmalhofer/keras-tensorflow-gpu:latest .
                mkdir -p ~/docker; docker save jonathanschmalhofer/keras-tensorflow-gpu:latest > ~/docker/image.tar
            - run: |
                mkdir /tmp/logs
                docker run -d jonathanschmalhofer/keras-tensorflow-gpu:latest "conda list; cat > test_environment.py <<EOL;import tensorflow as tf;mnist = tf.keras.datasets.mnist;(x_train, y_train), (x_test, y_test) = mnist.load_data();x_train, x_test = x_train / 255.0, x_test / 255.0;model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28, 28)),tf.keras.layers.Dense(512, activation=tf.nn.relu),tf.keras.layers.Dropout(0.2),tf.keras.layers.Dense(10, activation=tf.nn.softmax)]);model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy']);model.fit(x_train, y_train, epochs=5);model.evaluate(x_test,  y_test, verbose=2);EOL;cat test_environment.py;python test_environment.py" > /tmp/logs/dockerrun.log 2>&1
                cat /tmp/logs/dockerrun.log
            - run: |
                mkdir /tmp/artifacts
                ulimit -c unlimited
                docker save jonathanschmalhofer/keras-tensorflow-gpu:latest > /tmp/artifacts/keras-tensorflow-gpu.docker.tar
            - run: |
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                docker push jonathanschmalhofer/keras-tensorflow-gpu:latest
            - store_artifacts:
                path: /tmp/artifacts
            - store_artifacts:
                path: /tmp/logs